name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run unit tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Azure Login
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Spring Apps
        run: |
          az spring app deploy --name ${{ secrets.AZURE_SPRING_APPS_APP_NAME }} \
            --service ${{ secrets.AZURE_SPRING_APPS_SERVICE }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --artifact-path target/*.jar \

      - name: Build Docker image and Push to Registry
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-spring-app:latest .
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-spring-app:latest
